language: groovy
sudo: false
jdk:
- openjdk8
before_script:
- rm -rf target
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="Jeff Scott Brown"
  - GIT_EMAIL="brownj@objectcomputing.com"
  - secure: Ag9lKbDSp3NPCjQMDN4kvS5aswt3++pBvX8L6YHh84OhpgrPps7wLqlfiF7ETLntPdkwX3/fjkl4KHcI+SYHqVFTnpxIRbdOYXZhctyNNw1i2V8961nGvLRgS2nNByRpgf6CZI9hqbxk/jEQBiETlqYRqcMSg6IS7T0karG21v5bAU0B3+MtKQOrPp+tYA1xM2JyE++NDs2eeTk2EQ/Btltq3KKgx4fQf5UWkQ4wLVSiyeRz7WUoUYORCz0ZKRnpXgsvPAvqfwrqchApNP42C54f3OtPcxe86d9ySbN8HkMhmg7BrWWZp8QVr8iUIOP9vEHOzJ0BhYmNyIlXQkiyao7fkkpw44F9r2uofaZwzd/OAeXsxqlP3D5DbzwS7xpFPuQJQBSv/xLA/W0di/i0UDIRGQnVJVuB+iR1aHIkg6gTQrjd4iag8iBDqqYosmeKCy8VlPNFph9AcNX99CADHWhFZqULwChu+4PbqbvHgmjxip+ArHc2OvR34MptPq6N2pLnpYQxkni0/AOmZ5ugK1nBRfQf2RAkk7Q6zknMhVl+g49LuRgjDtDuK9wEotzjjnLVVlk1qt7qmXJLAPnXrgJ4SNJxCBgrgf41GDS/wDHu7ry8G+q2DW8mvSKqKxtuWfvDSQRbbPvpwBFtOb+AzHBxKJ7Fm64WKaWZBzG/u7c=
  - secure: b3FmUR/TZ6FD3qdXOd47WDQow7cc6JDZiPFmgnQRGHZ/v6FtYGzrMad8AntfM+10p5ai7D/bPlbYJzMnW8raJDVKhRxY+Dv8gnGPompVfYOZbQ/W414hLaneJNHXvYJe/JqrR1DqB2bBwQKGS9UAhQL1DOJkK747avNw60VAnRFz0iXi9lV8Atfuno2Dk5SX/u1zFRjCtPt6FQfv5wo/uqAKo5zNkprVAYrYvbnrjAZBWMa4/7S+PgPQ4y5pD3ZeYUjSEa6/3SOJ0AlF4ir87nirSgFMOkhC7L2lq5HX+znz1YCATM+Z3OUiU3Cbmt7KcrCHzt1DXCqjHUV7jlu0fW6KNSuR+QdWxdMusd0BxwJX23fCJmO5wbqosu5sOcxplHCnQcaVtHcqYW3fYFYmO/UkU8w6ML9pPwaMysuXHc4A+anXS8iCWIUOr513lENSDGixiRz+ZTPeUhMOvdMcQXbcpy3F81D7Tjg9tqSGpVbsckR2CvLCx3cOCR0hcipNbfc87Td6QpZI9TpTb8KcJT3gKHolfrg8LDzh+0DNghHNcCAL0g5K+eQMoZ8nhPdEG5TSRmpFuE133DDrSNR3MjEqdadFWYPnsBXERaoq9nFWk1woliooYw15vLpragLUioNVp/9HEyQ4oCrH3rIMSvrvTwm37YvWFbMCIu6R6Uo=
